import { getDepartmentWithAuth } from "@/actions/get-auth-department-actions";
import SiteContent from "@/components/layout/site-content";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Calendar - AttendifyX",
  description: "Generated by create next app",
};

export default async function Page() {
  const department = await getDepartmentWithAuth();
  return (
    <SiteContent title={"Calendar"}>
      <pre>
        <code>{JSON.stringify(department, null, 2)}</code>
      </pre>
    </SiteContent>
  );
}
