import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.css";
import Providers from "@/app/providers";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AttendifyX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.variable} font-sans`}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
