import EventClientPage from "@/app/(private)/events/client";
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Events - AttendifyX",
    description: "Generated by create next app",
};

export default function Page() {
    return <EventClientPage/>
}
